language: python

python:
      - 3.6
      #- 2.7

install:
      - pip install -r requirements.txt
      - pip install coveralls

script:
      - coverage run --source=ex_test setup.py test

after_success:
      - coveralls

#notifications:
#      slack:
#          secure: your_token_key

